### ISSUE TITLE
It should support responsive designs.

### ISSUE THREAD

**Issue by Kick933** [reslear/tailwind-scrollbar-hide#13]
There should be a overriding method so that we can show scrollbar on different screen sizes.
eg: className="scrollbar-hide md:scrollbar-default"

**Comment by StoraH** [comment]
Responsive classes don't work for me Ex. "md:scrollbar-default"

According to the [tailwind documentation](https://tailwindcss.com/docs/plugins#variants) desired variants needs to be added in the addUtilities call. 

Looks like none is added here https://github.com/reslear/tailwind-scrollbar-hide/blob/de969dd9c011f8a102ecc9287c3dcde1b4628c9f/src/index.js#L4
