### ISSUE TITLE
It should work with responsive design

### ISSUE THREAD

**Issue by Kick933** [reslear/tailwind-scrollbar-hide#18]
Scrollbar-hide class does not work with responsive designs.
I tried ```sm:scrollbar-hide``` and it did not work as expected.

**Comment by reslear** [comment]
have a repro?

**Comment by Kick933** [comment]
Oh, i was working on an old project and did not have latest package. 
My bad!
Also, I was thinking if we can have a variant for touch,although Tailwind has no builtin support for touch(coarse pointer) input variants.
