### ISSUE TITLE
In Desktop Cannot Scroll

### ISSUE THREAD

**Issue by prashantchothani** [reslear/tailwind-scrollbar-hide#21]
Using this plugin, with tailwind css 3.18, the scroll bar gets hidden. But in desktop cannot scroll with the mouse or keyboard.

**Comment by reslear** [comment]
hi, repro?
like this 
https://play.tailwindcss.com/DfHZcGih7B?size=598x720

**Comment by prashantchothani** [comment]
https://play.tailwindcss.com/O34guOHwtx

Made the above. If you check in desktop it does not scroll. If you have put the mouse over the div also you cannot drag, which you can do if the scrollbar is there

**Comment by prashantchothani** [comment]
You can check on devcms.foodxp.com/watch where we have used your excellent work. In mobile viewport you can drag the scroll but in desktop you cannot.

**Comment by reslear** [comment]
this is gestures for phone, not working in desktop, we need use grab cursor libraries, like [swiper](https://github.com/nolimits4web/swiper) )
