### ISSUE TITLE
Module "tailwind-scrollbar-hide/dist/index" has no default export.

### ISSUE THREAD

**Issue by mrleblanc101** [reslear/tailwind-scrollbar-hide#27]
I think we need an ESM `export default` version instead of CJS `module.exports`.
Or maybe we should move entirely to ESM instead of CJS ?

**Comment by f-elix** [comment]
Running into this issue as well. An ESM export would be great.

**Comment by reslear** [comment]
pls try [v2.0.0](https://github.com/reslear/tailwind-scrollbar-hide/releases/tag/v2.0.0)

**Comment by f-elix** [comment]
It works! Thanks for reacting so quickly :)
